- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
- name: restart prometheus
  systemd:
    name: prometheus
    daemon_reload: "{{ _prometheus_systemd | default ({}) is changed }}"
    state: restarted